version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

volumes:

  ravencoin-data:
    driver: local

services:

  ravencoin-wallet:
    build:
      context: .
      dockerfile: Dockerfile.wallet
    image: sofwerx/ravencoin-wallet
    container_name: ravencoin-wallet
    hostname: ravencoin-wallet
    logging: *default-logging
    volumes:
      - ravencoin-data:/root/.raven
    ports:
      - 127.0.0.1:8767:8767 # IPC - Keep protected!
      - 8767:8767           # Ravencoin blockchain traffic

  ravencoin-gpu-ccminer:
    build:
      context: .
      args:
        ARCH: ${ARCH}
      dockerfile: Dockerfile.gpu-ccminer.${ARCH}
    image: sofwerx/ravencoin-gpu-ccminer
    container_name: ravencoin-gpu-ccminer
    hostname: ravencoin-gpu-ccminer
    environment:
      URL: ${URL}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    logging: *default-logging

  ravencoin-cpu-cpuminer:
    build:
      context: .
      args:
        ARCH: ${ARCH}
      dockerfile: Dockerfile.cpu-cpuminer.${ARCH}
    image: sofwerx/ravencoin-cpu-cpuminer
    container_name: ravencoin-cpu-cpuminer
    hostname: ravencoin-cpu-cpuminer
    environment:
      URL: ${URL}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    logging: *default-logging

