version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

volumes:

  meowcoin-data:
    driver: local

services:

  meowcoin-wallet:
    build:
      context: .
      dockerfile: Dockerfile.wallet
    image: meowcoin-wallet
    container_name: meowcoin-wallet
    hostname: meowcoin
    logging: *default-logging
    volumes:
      - meowcoin-data:/home/meowcoin/.meowcoin
    #ports:
      #- 127.0.0.1:9766:9766 # Meowcoin blockchain traffic
      #- 8788:8788           # RPC - Keep protected!
