FROM ppc64le/ubuntu:16.04

RUN apt-get update
RUN apt-get install -y build-essential make automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++ git
RUN git clone https://github.com/tpruvot/cpuminer-multi /cpuminer

WORKDIR /cpuminer

#RUN autoreconf -fi
RUN aclocal \
 && autoheader \
 && automake --foreign --add-missing --force-missing --copy \
 && autoconf \
 && ./configure
RUN make

